language: python
python:
- '3.4'
sudo: false
install:
- pip install -e git+https://github.com/deconst/preparer-sphinx.git#egg=deconstrst
script:
- script/cibuild
env:
  global:
  - secure: UWevOWlEiRseoPPb6Kltwfa6B7YOSxhhtLp2pcB91+nKo8cAHX5NFFBV8W87qBvDN0XOQXaModUn1QLLUyWpijSnwAu3Gfk+Z5MQBzIqXmKVcwzUylbAzf5Px6qhCyBMUmVyMlLGEFwl3LVtNw0QO0wJ0/o5Nhx+kmziK8boY8w=
  - secure: JVOCrXu6TUOKZB8SNF1vRPARIsemUEUyhq5AzTE8QbbC5axJ9qPdBkV90kE5Ceup1aR56ThWMHLHQfymrrauyU0OJlWEmzQakyTLHWSjanquOzu+ND090MKragB4JR8b5uL1Abs1EGQbDlpNh6WbHdFFUdqLIQv4ira9hXJTBwg=
  - secure: MTdk56bdqxz7Q9vYhf8Stj6xOzKXyKCXjoaeBG9W+veaQ1dp6atJQTs7F8qdqWTUlzLxo/36SbbJrdgzHh4SNdQ1kwhizSXRUxU0SpwrKiR87lF+M2l1V6qEdoVY2b2Ps+xSPzg+0fDMSdkSVkoICnoenAv/BNfxH/jTj0pe8LE=
notifications:
  slack:
    secure: YVhTUEidfG/qXVQxtI7adtbTUUCGVjsVe4uDL7nNcH6oFYWrBem9MN6OGQrMPQXPOFJgd1/7Y9iueGE3qEoPkNv+ishLwe/A+YVUyai8DUyBNft97lNkEin/weJs79zYdPzkya/0cAN2wGj19RYf7HRpDwmxhWSQiwuku86Ms0s=
